// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSubscription(arg1, arg2) {
  return window['go']['main']['App']['AddSubscription'](arg1, arg2);
}

export function AddSubscriptionWithOptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSubscriptionWithOptions'](arg1, arg2, arg3);
}

export function ClearSpeedTestCache(arg1) {
  return window['go']['main']['App']['ClearSpeedTestCache'](arg1);
}

export function ConnectProfile(arg1) {
  return window['go']['main']['App']['ConnectProfile'](arg1);
}

export function ConnectSubscription(arg1) {
  return window['go']['main']['App']['ConnectSubscription'](arg1);
}

export function CreateProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2, arg3);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAutoReconnectOnUpdate() {
  return window['go']['main']['App']['GetAutoReconnectOnUpdate']();
}

export function GetCurrentSubscriptionID() {
  return window['go']['main']['App']['GetCurrentSubscriptionID']();
}

export function GetGroups(arg1) {
  return window['go']['main']['App']['GetGroups'](arg1);
}

export function GetPlatformInfo() {
  return window['go']['main']['App']['GetPlatformInfo']();
}

export function GetProfileConfig(arg1) {
  return window['go']['main']['App']['GetProfileConfig'](arg1);
}

export function GetProxyMode() {
  return window['go']['main']['App']['GetProxyMode']();
}

export function GetProxyPort() {
  return window['go']['main']['App']['GetProxyPort']();
}

export function GetSelectedNode(arg1) {
  return window['go']['main']['App']['GetSelectedNode'](arg1);
}

export function GetServers(arg1) {
  return window['go']['main']['App']['GetServers'](arg1);
}

export function GetServiceMode() {
  return window['go']['main']['App']['GetServiceMode']();
}

export function GetSpeedTestCache(arg1) {
  return window['go']['main']['App']['GetSpeedTestCache'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSubscriptionConfig(arg1) {
  return window['go']['main']['App']['GetSubscriptionConfig'](arg1);
}

export function GetTrafficStats() {
  return window['go']['main']['App']['GetTrafficStats']();
}

export function GetTunSettings() {
  return window['go']['main']['App']['GetTunSettings']();
}

export function InstallService() {
  return window['go']['main']['App']['InstallService']();
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function IsServiceInstalled() {
  return window['go']['main']['App']['IsServiceInstalled']();
}

export function IsServiceModeAvailable() {
  return window['go']['main']['App']['IsServiceModeAvailable']();
}

export function IsServiceRunning() {
  return window['go']['main']['App']['IsServiceRunning']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListSubscriptions() {
  return window['go']['main']['App']['ListSubscriptions']();
}

export function RefreshServiceClient() {
  return window['go']['main']['App']['RefreshServiceClient']();
}

export function SelectGroup(arg1, arg2) {
  return window['go']['main']['App']['SelectGroup'](arg1, arg2);
}

export function SelectServer(arg1, arg2) {
  return window['go']['main']['App']['SelectServer'](arg1, arg2);
}

export function SetAutoReconnectOnUpdate(arg1) {
  return window['go']['main']['App']['SetAutoReconnectOnUpdate'](arg1);
}

export function SetProxyMode(arg1) {
  return window['go']['main']['App']['SetProxyMode'](arg1);
}

export function SetProxyPort(arg1) {
  return window['go']['main']['App']['SetProxyPort'](arg1);
}

export function SetServiceMode(arg1) {
  return window['go']['main']['App']['SetServiceMode'](arg1);
}

export function SetTunSettings(arg1) {
  return window['go']['main']['App']['SetTunSettings'](arg1);
}

export function SpeedTest(arg1) {
  return window['go']['main']['App']['SpeedTest'](arg1);
}

export function SpeedTestNode(arg1, arg2) {
  return window['go']['main']['App']['SpeedTestNode'](arg1, arg2);
}

export function SpeedTestNodes(arg1, arg2) {
  return window['go']['main']['App']['SpeedTestNodes'](arg1, arg2);
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}

export function UninstallService() {
  return window['go']['main']['App']['UninstallService']();
}

export function UpdateProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2, arg3, arg4);
}

export function UpdateSubscription(arg1) {
  return window['go']['main']['App']['UpdateSubscription'](arg1);
}

export function UpdateSubscriptionOptions(arg1, arg2) {
  return window['go']['main']['App']['UpdateSubscriptionOptions'](arg1, arg2);
}
