// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {subscription} from '../models';
import {settings} from '../models';

export function AddSubscription(arg1:string,arg2:string):Promise<string>;

export function AddSubscriptionWithOptions(arg1:string,arg2:string,arg3:subscription.SubscriptionOptions):Promise<string>;

export function ClearSpeedTestCache(arg1:string):Promise<void>;

export function ConnectProfile(arg1:string):Promise<void>;

export function ConnectSubscription(arg1:string):Promise<void>;

export function CreateProfile(arg1:string,arg2:Array<string>,arg3:string):Promise<string>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteSubscription(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetAutoReconnectOnUpdate():Promise<boolean>;

export function GetCurrentSubscriptionID():Promise<string>;

export function GetGroups(arg1:string):Promise<Array<Record<string, any>>>;

export function GetPlatformInfo():Promise<Record<string, string>>;

export function GetProfileConfig(arg1:string):Promise<string>;

export function GetProxyMode():Promise<string>;

export function GetProxyPort():Promise<number>;

export function GetSelectedNode(arg1:string):Promise<string>;

export function GetServers(arg1:string):Promise<Array<Record<string, any>>>;

export function GetServiceMode():Promise<boolean>;

export function GetSpeedTestCache(arg1:string):Promise<Record<string, number>>;

export function GetStatus():Promise<string>;

export function GetSubscriptionConfig(arg1:string):Promise<string>;

export function GetTrafficStats():Promise<Record<string, number>>;

export function GetTunSettings():Promise<settings.TunSettings>;

export function InstallService():Promise<void>;

export function IsAdmin():Promise<boolean>;

export function IsServiceInstalled():Promise<boolean>;

export function IsServiceModeAvailable():Promise<boolean>;

export function IsServiceRunning():Promise<boolean>;

export function ListProfiles():Promise<Array<Record<string, any>>>;

export function ListSubscriptions():Promise<Array<Record<string, any>>>;

export function RefreshServiceClient():Promise<boolean>;

export function SelectGroup(arg1:string,arg2:string):Promise<void>;

export function SelectServer(arg1:string,arg2:string):Promise<void>;

export function SetAutoReconnectOnUpdate(arg1:boolean):Promise<void>;

export function SetProxyMode(arg1:string):Promise<void>;

export function SetProxyPort(arg1:number):Promise<void>;

export function SetServiceMode(arg1:boolean):Promise<void>;

export function SetTunSettings(arg1:settings.TunSettings):Promise<void>;

export function SpeedTest(arg1:string):Promise<Record<string, number>>;

export function SpeedTestNode(arg1:string,arg2:string):Promise<number>;

export function SpeedTestNodes(arg1:string,arg2:Array<string>):Promise<Record<string, number>>;

export function StartService():Promise<void>;

export function StopService():Promise<void>;

export function UninstallService():Promise<void>;

export function UpdateProfile(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;

export function UpdateSubscription(arg1:string):Promise<void>;

export function UpdateSubscriptionOptions(arg1:string,arg2:subscription.SubscriptionOptions):Promise<void>;
